#!/usr/bin/env sh
## Adds an item from a specified file to the podcast xml file

while getopts f:g:t:u:l:d: flag
do
    case "${flag}" in
        f) file=${OPTARG};;
        g) guid=${OPTARG};;
        u) url=${OPTARG};;
        l) length=${OPTARG};;
        d) duration=${OPTARG};;
    esac
done

# Delete last two lines of the file
sed -i '$d' $file
sed -i '$d' $file

# Add the item
cat >> $file << EOF
    <item>
      <guid>$guid</guid>
      <title>$guid</title>
      <link></link>
      <description></description>
      <pubDate>Thu, 01 Apr 2021 15:27:52 +0000</pubDate>
      <enclosure url="$url/$guid.m4a" length="$length" type="audio/mpeg"></enclosure>
      <itunes:author>Test podcast</itunes:author>
      <itunes:subtitle>$title</itunes:subtitle>
      <itunes:summary><![CDATA[]]></itunes:summary>
      <itunes:image href="https://image.freepik.com/free-vector/illustration-headphones-icon_53876-5571.jpg"></itunes:image>
      <itunes:duration>$duration</itunes:duration>
      <itunes:explicit>no</itunes:explicit>
      <itunes:order>1</itunes:order>
    </item>
  </channel>
</rss>
EOF
