#!/usr/bin/env sh
## Sets the display brightness to match battery level

if ! [ -w /sys/class/backlight/intel_backlight/brightness ]; then
    echo "This script requires /sys/class/backlight/intel_backlight/brightness to be writeable by the user...."
    exit 2
fi

battery_percentage=$(paste /sys/class/power_supply/BAT0/capacity)
max_brightness=$(paste /sys/class/backlight/intel_backlight/max_brightness)
set_brightness=$(((battery_percentage*10/15*max_brightness/100)))
battery_state=$(paste /sys/class/power_supply/BAT0/status)

if [ "$battery_state" = "Charging" ] || [ "$battery_state" = "Not charging" ]; then
    echo "$max_brightness" > /sys/class/backlight/intel_backlight/brightness
    printf "%s" "Setting backlight to $(((max_brightness*100/max_brightness)))%"
else
    if [  "$battery_percentage" = "100" ]; then
        echo "$max_brightness" > /sys/class/backlight/intel_backlight/brightness
        printf "%s" "Setting backlight to $(((max_brightness*100/max_brightness)))%"
    else
        echo "$set_brightness" > /sys/class/backlight/intel_backlight/brightness
        printf "%s" "Setting backlight to $(((set_brightness*100/max_brightness)))%"
    fi
fi
