#!/usr/bin/env sh
## fuzzy cd using fzf

# Locate file
#file=$(locate -Ai -0 '$@' | grep -z -vE '~$' | fzf --read0 -0 -1)
file=$(locate -Ai -0 "$1" | fzf --read0 -0 -1)

# Checks if file was found, exits if it wasn't
# If file exists and if file is a dir, change to dir, otherwise change to file's dir
[ -z "$file" ] && echo "That file cannot be located..."  || [ -d "$file" ] && cd "$file" || cd "${file:h}"
