#!/usr/bin/env sh
## Checks daily corona stats

COUNTRY="Australia"

# Test if file is older than 6hrs and get new data if it is
test "$(/usr/bin/find $XDG_CACHE_HOME/corona -mmin +1)" &&
curl --silent "https://corona-stats.online/$COUNTRY?format=json&source=1" -o $XDG_CACHE_HOME/corona


CASES=$(jq '.[] | select(.province == "Western Australia") | .confirmed' $XDG_CACHE_HOME/corona)
DAILY_INC_CASES=$(jq '.[] | select(.province == "Western Australia") | .confirmedByDay[-1] - .confirmedByDay[-2]' $XDG_CACHE_HOME/corona)
DAILY_DELTA=$(jq '.[] | select(.province == "Western Australia") | .confirmedByDay[-1] - .confirmedByDay[-2] - .confirmedByDay[-2] + .confirmedByDay[-3]' $XDG_CACHE_HOME/corona)
DEATHS=$(jq '.[] | select(.province == "Western Australia") | .deathsByDay[-1]' $XDG_CACHE_HOME/corona)
MORTALITY=$(jq '.[] | select(.province == "Western Australia") | .mortalityPer' $XDG_CACHE_HOME/corona | sed "s/\"//g")

#OUTPUT="!${CASES}(${DAILY_INC_CASES} 喝${DAILY_DELTA}) ${DEATHS}(${MORTALITY}%)"
OUTPUT="N${CASES}(+${DAILY_INC_CASES}喝${DAILY_DELTA})(${DEATHS})"

echo "${OUTPUT}"
