#!/usr/bin/env zsh
## Script to push all my git repos at the same time

#repos=$(/usr/bin/ls $HOME/Git)

if [[ $(ssh-add -l) == 0 ]]; then
    ssh-add
fi

#for i in "${repos}"; do
for i in "$HOME/git"/*; do
    cd "$i"
    $HOME/git/scripts/shell/gitpush
done
