#!/usr/bin/env sh
## Push all patches in a loop

number_of_patches_left=$(git status --short | wc -l)

while [ "$number_of_patches_left" -gt 0 ]; do
    git pull
    git add --patch
    pre-commit run
    cz c
    number_of_patches_left=$(git status --short | wc -l)
done
