#!/bin/zsh
# Split a text file into smaller GPT compatible chunks

usage() {                                 # Function: Print a help message.
    echo "Usage: $0 [ -f FILE ]" 1>&2
}

exit_abnormal() {                         # Function: Exit with error.
    usage
    exit 1
}
while getopts f: flag

do
    case "${flag}" in
        f)
            FILE=${OPTARG}
            ;;
        :)                                    # If expected argument omitted:
            echo "Error: -${OPTARG} requires an argument."
            exit_abnormal                       # Exit abnormally.
            ;;
        *)                                    # If unknown (any other) option:
            exit_abnormal                       # Exit abnormally.
            ;;
    esac
done

rm /tmp/gpt*

SESSION=$(tr -dc A-Za-z0-9 </dev/urandom | head -c 13)

chatblade --chat-gpt gpt-3.5-turbo-16k --session $SESSION 'The total length of the content that I want to send you is too large to send in only one piece.\n\nFor sending you that content, I will follow this rule:\n\n[START PART 1/10]\nthis is the content of the part 1 out of 10 in total\n[END PART 1/10]\n\nThen you just answer: "Received part n/x"\n\nAnd when I tell you "ALL PARTS SENT", then you can continue processing the data and answering my requests.'

split "$FILE" /tmp/gpt -l 200 --numeric-suffixes=01

NUMBER_OF_FILES=$(find /tmp -name 'gpt*' | wc -l)

n=1
for GPT_FILE in $(find /tmp -name 'gpt*' | sort); do
    sed -i -e "1iDo not answer yet. This is just another part of the text I want to send you. Just receive and acknowledge as 'Part ${n}/${NUMBER_OF_FILES} received' and wait for the next part.\n[START PART ${n}/${NUMBER_OF_FILES}]" $GPT_FILE
    echo '[END PART '$n'/'$NUMBER_OF_FILES']\nRemember not answering yet. Just acknowledge you received this part with the message "Part '$n'/'$NUMBER_OF_FILES' received" and wait for the next part.' >> $GPT_FILE
    n=$((n+1))
    grep -v '^[0-9]' $GPT_FILE | chatblade --chat-gpt gpt-3.5-turbo-16k --session $SESSION
done

chatblade --chat-gpt gpt-3.5-turbo-16k --session $SESSION "ALL PARTS SENT. Now you can continue processing the request."
chatblade --chat-gpt gpt-3.5-turbo-16k --session $SESSION --interactive
