#!/usr/bin/env sh
## Curls a UrL, the opens it in imv

IMGDIR="/tmp"

for url in "$@"
do
    filename="`echo \"$url\" | sed -E 's,^(.*/)*([^/]+)$,\2,'`"
    curl -so "$IMGDIR/$filename" "$url" && echo "$IMGDIR/$filename"
done | imv | sort | uniq | /usr/bin/rm "$IMGDIR/$filename"
