#!/usr/bin/env sh
# Runs rofi with a yes/no option
# Gives a dmenu prompt labeled with $1 to perform command $2.
# For example:
# `./rofi_yesno "Do you want to shutdown?" "shutdown -h now"`

[ $(printf "Yes\nNo" | rofi -dmenu -i -mesg "$1" -select -only-match) = 'Yes' ] && zsh -c "$2"
