#!/usr/bin/env zsh
## Use aria2c to seed my torrents

killall -9 aria2c

for file in $(/usr/bin/fd . /mnt/sshfs/sport --hidden -e torrent); do
    file_name=$(echo "$file" | rev | cut -d'/' -f1 | cut -d'.' -f2- | rev | cut -d'.' -f2-)
    directory=$(dirname "$file")
    aria2c --check-integrity=true --seed-ratio=0.0 --continue --bt-force-encryption --bt-require-crypto --bt-max-peers=0 --bt-detach-seed-only --bt-seed-unverified "$file" --dir "$directory" --select-file=1 --index-out=1="$file_name".mkv > /dev/null 2>&1 & disown
done
