#!/usr/bin/env zsh
## Allows user to enter shutdown_in hh:mm:ss and gives a countdown

# Tests the format that time_in is given by counting how many ":" there are
timein=$1
delimiter=":"
numberOfDelimiters=$(grep -o "$delimiter" <<< $timein | wc -l)

# If number of delims is 1 then assume argument is seconds, 3 is hh:mm:ss
if [[ $numberOfDelimiters == "1" ]]; then
    ((time_ts=$(echo "$1" | awk -F: '{ print ($1*60) + $2 }')))
elif [[ $numberOfDelimiters == "2" ]]; then
    ((time_ts=$(echo "$1" | awk -F: '{ print ($1*60*60) + ($2*60) + $3 }')))
elif [[ $numberOfDelimiters == "3" ]]; then
    ((time_ts=$(echo "$1" | awk -F: '{ print ($1*24*60*60) + ($2*60*60) + ($3*60) + $4 }')))
fi

# Countdown in terminal
while [[ $time_ts -gt 0 ]]; do
    echo -ne "Shutdown will occur in $(date -u -d @$time_ts +'%T')......\033[0K\r"
    sleep 1
    ((time_ts--))
done

# Had to set linux to run shutdown without confirmation
systemctl poweroff
