# coding: utf-8

"""
    Jellyfin API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 10.10.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.string_group_update import StringGroupUpdate

class TestStringGroupUpdate(unittest.TestCase):
    """StringGroupUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StringGroupUpdate:
        """Test StringGroupUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StringGroupUpdate`
        """
        model = StringGroupUpdate()
        if include_optional:
            return StringGroupUpdate(
                group_id = '',
                type = 'UserJoined',
                data = ''
            )
        else:
            return StringGroupUpdate(
        )
        """

    def testStringGroupUpdate(self):
        """Test StringGroupUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
