# coding: utf-8

"""
    Jellyfin API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 10.10.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.group_state_update_group_update import GroupStateUpdateGroupUpdate

class TestGroupStateUpdateGroupUpdate(unittest.TestCase):
    """GroupStateUpdateGroupUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GroupStateUpdateGroupUpdate:
        """Test GroupStateUpdateGroupUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GroupStateUpdateGroupUpdate`
        """
        model = GroupStateUpdateGroupUpdate()
        if include_optional:
            return GroupStateUpdateGroupUpdate(
                group_id = '',
                type = 'UserJoined',
                data = openapi_client.models.group_state_update.GroupStateUpdate(
                    state = 'Idle', 
                    reason = 'Play', )
            )
        else:
            return GroupStateUpdateGroupUpdate(
        )
        """

    def testGroupStateUpdateGroupUpdate(self):
        """Test GroupStateUpdateGroupUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
