# coding: utf-8

"""
    Jellyfin API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 10.10.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.sync_play_group_update_command_message import SyncPlayGroupUpdateCommandMessage

class TestSyncPlayGroupUpdateCommandMessage(unittest.TestCase):
    """SyncPlayGroupUpdateCommandMessage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SyncPlayGroupUpdateCommandMessage:
        """Test SyncPlayGroupUpdateCommandMessage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SyncPlayGroupUpdateCommandMessage`
        """
        model = SyncPlayGroupUpdateCommandMessage()
        if include_optional:
            return SyncPlayGroupUpdateCommandMessage(
                data = openapi_client.models.group_update.GroupUpdate(
                    group_id = '', ),
                message_id = '',
                message_type = 'ForceKeepAlive'
            )
        else:
            return SyncPlayGroupUpdateCommandMessage(
        )
        """

    def testSyncPlayGroupUpdateCommandMessage(self):
        """Test SyncPlayGroupUpdateCommandMessage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
