# coding: utf-8

"""
    Jellyfin API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 10.10.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.wake_on_lan_info import WakeOnLanInfo

class TestWakeOnLanInfo(unittest.TestCase):
    """WakeOnLanInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WakeOnLanInfo:
        """Test WakeOnLanInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WakeOnLanInfo`
        """
        model = WakeOnLanInfo()
        if include_optional:
            return WakeOnLanInfo(
                mac_address = '',
                port = 56
            )
        else:
            return WakeOnLanInfo(
        )
        """

    def testWakeOnLanInfo(self):
        """Test WakeOnLanInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
