# coding: utf-8

"""
    Jellyfin API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 10.10.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.group_info_dto_group_update import GroupInfoDtoGroupUpdate

class TestGroupInfoDtoGroupUpdate(unittest.TestCase):
    """GroupInfoDtoGroupUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GroupInfoDtoGroupUpdate:
        """Test GroupInfoDtoGroupUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GroupInfoDtoGroupUpdate`
        """
        model = GroupInfoDtoGroupUpdate()
        if include_optional:
            return GroupInfoDtoGroupUpdate(
                group_id = '',
                type = 'UserJoined',
                data = openapi_client.models.group_info_dto.GroupInfoDto(
                    group_id = '', 
                    group_name = '', 
                    state = 'Idle', 
                    participants = [
                        ''
                        ], 
                    last_updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else:
            return GroupInfoDtoGroupUpdate(
        )
        """

    def testGroupInfoDtoGroupUpdate(self):
        """Test GroupInfoDtoGroupUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
