#!/usr/bin/env zsh

# cd including hidden directories
fuzzy_cd () {
    dir="$(
        fd --hidden --no-ignore --type d . ~ \
            | fzf +m \
            --tac \
            --preview='tree -C {} | head -n $FZF_PREVIEW_LINES' \
            --preview-window='bottom' \
            --query="$1" \
            --multi \
            --select-1 \
            --exit-0
        )" || return
    cd "$dir" || return
}

fuzzy_cd
