[project]
name = "modrinth-checker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "packaging>=25.0",
    "questionary>=2.1.0",
    "rich>=14.0.0",
    "typer>=0.15.3",
]
