[project]
name = "bookmarks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "arrow>=1.3.0",
    "httpx>=0.28.1",
    "polars>=1.21.0",
    "pytest>=8.3.4",
    "regex>=2024.11.6",
    "typer>=0.15.1",
]
