[project]
name = "youtube-playlist-creator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
<<<<<<< HEAD
    "bowler>=0.9.0",
    "httpx>=0.27.2",
    "loguru>=0.7.2",
    "orjson>=3.10.11",
    "pydantic>=2.9.2",
    "pyupgrade>=3.19.0",
    "questionary>=2.0.1",
    "tenacity>=9.0.0",
    "tinydb>=4.8.2",
||||||| parent of 3b601b7 (first folder)
=======
    "httpx>=0.27.2",
    "loguru>=0.7.2",
    "pydantic>=2.9.2",
>>>>>>> 3b601b7 (first folder)
    "typer>=0.12.5",
]
