[project]
name = "podsync-xml-creator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "arrow>=1.3.0",
    "loguru>=0.7.3",
    "questionary>=2.1.0",
    "rich>=14.1.0",
]
