#!/bin/zsh
# Feed this script a link and it will give dmenu
# some choice programs to use to open it.

x=$(echo -e "clip->primary\nprimary->clip\npaste" | dmenu -h 40 -fn "CodeNewRoman Nerd Font:pixelsize=15;1" -i -p "Where should I copy to/from?")
case "$x" in
    "clip->primary") xsel -ob | xsel -ip ;;
    "primary->clip") xsel -op | xsel -ib ;;
    "paste") xsel -ob | xsel -ip && xsel -op ;;
esac
